### ISSUE TITLE
I2C class instantiation in TMP100 class

### ISSUE THREAD

**Issue by StefanoSperetta** [Markiv9999/STM32NUCLEOBUS#5]
[This](https://github.com/Markiv9999/STM32NUCLEOBUS/blob/2af3cfbe3922883b277fc7a064beb996e60660de/Core/Inc/TMP100.h#L35C2-L35C13) syntax instantiates a I2C_IT class inside a TMP100 class when the constructor is invoked (see [this](https://github.com/Markiv9999/STM32NUCLEOBUS/blob/2af3cfbe3922883b277fc7a064beb996e60660de/Core/Src/TMP100.cpp#L11)).

This means that, if 2x TMP100 classes are instantiated (because 2x TMP100 sensors exist) and they are connected to the same I2C peripheral, we have 2x I2C classes pointing to the same peripheral.

[This line](https://github.com/Markiv9999/STM32NUCLEOBUS/blob/2af3cfbe3922883b277fc7a064beb996e60660de/Core/Inc/TMP100.h#L35) should become:

```  I2C_IT &i2c;```

The reference makes sure the object is not instantiated twice but only a reference is created.

[This line](https://github.com/Markiv9999/STM32NUCLEOBUS/blob/2af3cfbe3922883b277fc7a064beb996e60660de/Core/Src/TMP100.cpp#L11) should become:

``` TMP100::TMP100(uint8_t tempaddress,I2C_IT &hi2c) : i2c(hi2c) ```

The delay variable is used by the I2C class so it is not needed anymore in the TMP100 class and can be removed.

**Comment by Markiv9999** [comment]
Changed the object to be by reference inside the TMP100 class. The delay variable is defined in the I2C class and can be specified when declaring the object, or defaults to HAL_MAX_DELAY.
