### ISSUE TITLE
Temporary vs class variables

### ISSUE THREAD

**Issue by StefanoSperetta** [Markiv9999/STM32NUCLEOBUS#6]
[Here](https://github.com/Markiv9999/STM32NUCLEOBUS/blob/7ae9ccaaf5dc09d4863cb436669428e61873eb41/Core/Inc/TMP100.h#L34) the return code from I2C calls is stored as class member and it is later returned. This prevents the compiler from optimizing the return variable as it is required to be stored in memory.

Ret should be defined as a local variable in the function returning it: this will hint the compiler the variable is only used till returning it and can force the optimizer to optimize it.

**Comment by Markiv9999** [comment]
Got it !! Changed ret to local variable in TMP100 functions.
